spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
         format_sql: true
        # show_sql: true
        # use_sql_comments: true  #jpql 형태로 출력
logging:
  level:
    org:
      hibernate:
        SQL: debug
